#cloud-config
system_info:
  default_user:
    name: ait
    plain_text_passwd: test
    lock_passwd: False
write_files:
  -   encoding: b64
      content: IyEvYmluL2Jhc2gKCk5FVFBMQU49Ii9ldGMvbmV0cGxhbi81MC1jbG91ZC1pbml0LnlhbWwiCgpNQUlOSUY9YGlwIGxpbmsgc2hvdyB8IGdyZXAgVVAgfCBncmVwIC12IExPT1BCQUNLIHwgYXdrICd7cHJpbnQgJDJ9JyB8IHJldiB8IGN1dCAtYyAyLSB8IHJldiB8IGhlYWQgLW4gMWAKTUFJTk1BQz1gY2F0IC9zeXMvY2xhc3MvbmV0LyRNQUlOSUYvYWRkcmVzc2AKCmZ1bmN0aW9uIHByaW50bmV0Y29uZmlnKCkKewogICAgZWNobyAiICAgICAgICAgICAgbWF0Y2g6IgogICAgZWNobyAiICAgICAgICAgICAgICAgIG1hY2FkZHJlc3M6ICckMSciCgllY2hvICIgICAgICAgICAgICBkaGNwNDogdHJ1ZSIKCWVjaG8gIiAgICAgICAgICAgIGRoY3A0LW92ZXJyaWRlczoiCgllY2hvICIgICAgICAgICAgICAgICAgdXNlLXJvdXRlczogZmFsc2UiCn0KCmVjaG8gIm5ldHdvcms6IiA+ICRORVRQTEFOCmVjaG8gIiAgICBldGhlcm5ldHM6IiA+PiAkTkVUUExBTgplY2hvICIgICAgICAgICRNQUlOSUY6IiA+PiAkTkVUUExBTgplY2hvICIgICAgICAgICAgICBkaGNwNDogdHJ1ZSIgPj4gJE5FVFBMQU4KZWNobyAiICAgICAgICAgICAgbWF0Y2g6IiA+PiAkTkVUUExBTgplY2hvICIgICAgICAgICAgICAgICAgbWFjYWRkcmVzczogJyRNQUlOTUFDJyIgPj4gJE5FVFBMQU4KZm9yIElGIGluIGBpcCBsaW5rIHNob3cgfCBncmVwIG10dSB8IGdyZXAgLXYgTE9PUEJBQ0sgfCBncmVwIC12ICIkTUFJTklGIiB8IGF3ayAne3ByaW50ICQyfScgfCByZXYgfCBjdXQgLWMgMi0gfCByZXZgCmRvCmVjaG8gIiAgICAgICAgJElGOiIgPj4gJE5FVFBMQU4KcHJpbnRuZXRjb25maWcgJChjYXQgL3N5cy9jbGFzcy9uZXQvJElGL2FkZHJlc3MpID4+ICRORVRQTEFOCmRvbmUKZWNobyAiICAgIHZlcnNpb246IDIiID4+ICRORVRQTEFOCgplY2hvICJuZXR3b3JrOiB7Y29uZmlnOiBkaXNhYmxlZH0iID4gL2V0Yy9jbG91ZC9jbG91ZC5jZmcuZC85OS1kaXNhYmxlLW5ldHdvcmstY29uZmlnLmNmZwoKL3Vzci9zYmluL25ldHBsYW4gYXBwbHkK
      owner: root:root
      path: /root/ifsetup.sh
      permissions: '0700'
runcmd:
  - [ /root/ifsetup.sh ]
  -  [apt-get, update]
  -  [apt-get, install, -y, python]
